### ISSUE TITLE
./mirror server gives error ./mirror: line 9: java: command not found

### ISSUE THREAD

**Issue by goosehub** [stephenh/mirror#3]
I am attempting to set up ./mirror, and have gotten to the step of running

    ./mirror server

That gives the error

    ./mirror: line 9: java: command not found

I have replicated this issue on two boxes. If I am making a mistake, please let me know. If this is an issue, please fix and let me know what I can do to help. Thank you!

**Comment by goosehub** [comment]
I just installed Java with

    sudo apt-get install openjdk-7-jre

and got this error

    Exception in thread "main" java.lang.UnsupportedClassVersionError: mirror/Mirror : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by goosehub** [comment]
java -version

gives me

```
java version "1.7.0_131"
OpenJDK Runtime Environment (IcedTea 2.6.9) (7u131-2.6.9-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.131-b00, mixed mode)
```

**Comment by stephenh** [comment]
Hi, thanks for reporting this! I had not documented it (I'll add it to the readme), but mirror requires Java 8. Can you install openjdk-8-jre and see if that works?

**Comment by goosehub** [comment]
Unfortunately I've already found another tool for this task. Also, I'm not familiar with Java. Thanks for quickly getting back to me though!

**Comment by stephenh** [comment]
Np, the communication is still appreciated to help the next person. Good luck!
