### ISSUE TITLE
"Increasing file limit to 9223372036854775807" and NullPointerException on "mirror client" startup

### ISSUE THREAD

**Issue by ajdavis** [stephenh/mirror#30]
I just installed mirror on my macOS 10.13.6 laptop, and "mirror client" fails at startup:
```
> mirror client
2019-01-19 09:35:09 INFO  Increasing file limit to 9223372036854775807
Exception in thread "main" java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at mirror.Mirror$MirrorClientCommand.runIfChecksOkay(Mirror.java:191)
	at mirror.Mirror$BaseCommand.run(Mirror.java:100)
	at mirror.Mirror.main(Mirror.java:55)
```
This seems to happen no matter what options I pass. "mirror server" succeeds:
```
> mirror server
2019-01-19 09:36:09 INFO  Increasing file limit to 9223372036854775807
2019-01-19 09:36:10 INFO  Listening on 49172, version unspecified
```
I installed mirror like:
```
wget http://repo.joist.ws/mirror-all.jar ~/
wget http://repo.joist.ws/mirror ~/
```

**Comment by ajdavis** [comment]
```
> java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by ajdavis** [comment]
Oh, this happens if I don't pass "-r" to "mirror client". I think mirror needs more helpful argument checking. =)
