### ISSUE TITLE
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.facebook.watchman.WatchmanException: unknown command watch-project

### ISSUE THREAD

**Issue by rameshar16** [stephenh/mirror#57]
Hi @stephenh,

I am getting the below error on the client-side.
**
2020-04-25 16:51:53 INFO  Connected, starting session, version 1.3.6-3-gb47dd9f-dirty
2020-04-25 16:51:53 ERROR Exception starting the client
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.facebook.watchman.WatchmanException: unknown command watch-project
        at mirror.watchman.WatchmanImpl.run(WatchmanImpl.java:67)
        at mirror.watchman.WatchmanFileWatcher.startWatchAndInitialFind(WatchmanFileWatcher.java:179)
        at mirror.watchman.WatchmanFileWatcher.performInitialScan(WatchmanFileWatcher.java:132)
        at mirror.MirrorSession.calcInitialState(MirrorSession.java:77)
        at mirror.MirrorClient.startSession(MirrorClient.java:88)
        at mirror.MirrorClient.access$300(MirrorClient.java:27)
        at mirror.MirrorClient$SessionStarter.runOneLoop(MirrorClient.java:198)
        at mirror.tasks.ThreadBasedTask.run(ThreadBasedTask.java:62)
        at mirror.tasks.ThreadBasedTask.lambda$new$0(ThreadBasedTask.java:39)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.facebook.watchman.WatchmanException: unknown command watch-project
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:512)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
        at mirror.watchman.WatchmanImpl.run(WatchmanImpl.java:65)
        ... 9 common frames omitted
Caused by: com.facebook.watchman.WatchmanException: unknown command watch-project
        at com.facebook.watchman.WatchmanConnection$IncomingMessageThread.run(WatchmanConnection.java:257)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted
2020-04-25 16:51:53 INFO  Stopping session
**

I have downloaded the watchman from the https://download.copr.fedorainfracloud.org/results/codeblock/watchman/epel-6-x86_64/watchman-2.9.5-1.fc20/watchman-2.9.5-1.el6.x86_64.rpm" and installed it on both servers.

Please help me in fixing the issue and let me know if I missed anything.

Thanks and Regards,
Ramesh AR

**Comment by stephenh** [comment]
That version of watchman is really old. Try getting 4.9.0 from https://facebook.github.io/watchman/.
