### ISSUE TITLE
on debian client fails

### ISSUE THREAD

**Issue by emard** [stephenh/mirror#71]
this is what I did, on each node there is empty directories to mirror
server starts but client fails with error. Seems I need help to get it working

apt install watchman

    wget https://github.com/stephenh/mirror/releases/latest/download/mirror-all.jar ~/
    wget https://github.com/stephenh/mirror/releases/latest/download/mirror ~/

root@nod2:~# java -version
openjdk version "17.0.8-ea" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8-ea+6-Debian-3)
OpenJDK 64-Bit Server VM (build 17.0.8-ea+6-Debian-3, mixed mode, sharing)
root@nod2:~# ls /home/davor/mirror
root@nod2:~# /opt/mirror/bin/mirror server
2023-07-10 13:09:43 ERROR Your system inotify limits look too low (they are probably the default values)
2023-07-10 13:09:43 INFO    Your max_queued_events is 16384 and should probably be increased
2023-07-10 13:09:43 INFO    E.g.: echo fs.inotify.max_queued_events=50000 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
2023-07-10 13:09:43 INFO
2023-07-10 13:09:43 INFO    See https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
2023-07-10 13:09:43 INFO    Or use --skip-limit-checks to ignore this
2023-07-10 13:09:44 INFO  Listening on 0.0.0.0:49172, version 1.3.11

root@nod1:~# java -version
openjdk version "17.0.8-ea" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8-ea+6-Debian-3)
OpenJDK 64-Bit Server VM (build 17.0.8-ea+6-Debian-3, mixed mode, sharing)
root@nod1:~# ls /home/davor/mirror
root@nod1:~# /opt/mirror/bin/mirror client nod2 -l /home/davor/mirror -r /home/davor/mirror/
Exception in thread "main" com.github.rvesse.airline.parser.errors.ParseArgumentsUnexpectedException: Found unexpected parameters: [nod2]
        at com.github.rvesse.airline.restrictions.global.NoUnexpectedArgumentsRestriction.validate(NoUnexpectedArgumentsRestriction.java:27)
        at com.github.rvesse.airline.parser.command.CliParser.validate(CliParser.java:73)
        at com.github.rvesse.airline.parser.command.CliParser.parseWithResult(CliParser.java:48)
        at com.github.rvesse.airline.parser.command.CliParser.parse(CliParser.java:53)
        at com.github.rvesse.airline.Cli.parse(Cli.java:127)
        at com.github.rvesse.airline.Cli.parse(Cli.java:113)
        at mirror.Mirror.main(Mirror.java:58)

**Comment by stephenh** [comment]
Hi @emard 

```
/opt/mirror/bin/mirror client nod2 -l /home/davor/mirror -r /home/davor/mirror/
```

I think you're missing a `-h` between `client` and `nod2`

**Comment by emard** [comment]
It was just a missing option, now it works!
Thank you!
